------------------
-- Instructions --
------------------

-- This is a Lua file containing all the text in the game.
-- To translate the text in the game change the strings to their translated versions.
-- Some things to note is that since double quotes are needed to enclose the strings, they need to be escaped
-- if they are needed inside a string, by writing them as \" (see t[99] as an example).
--
-- The comments at the end of each line give some additional information about the text.
-- Text tagged as INES, PRESIDENT_INES, LEE, HOLEEGRAM, COLLECTOR, ANDREA, PAOLO, PEPPE is text that appears as spoken
-- dialogue, and the tag indicates which character is speaking.
-- PEPPE, PAOLO, and ANDREA are the three musicians in the sixties, from left to right.
-- Text tagged as LOOK appears only as the description of an object/hotspot when the cursor is above it.
-- Text tagged as ECHO appears as a dialogue option that is also spoken by the protagonist when selected.
-- Text tagged as NOECHO appears only as a dialogue option but is not spoken.
-- Text tagged as TEXT
--
-- If the language you are translating into does not use spaces between words you will need to break lines manually
-- inside the text that needs to wrap (text spoken by the characters, as well as LOOK and ECHO tags).
-- Line breaks are encoded as \n inside Lua strings. You can test how the text will be displayed with the provided online tester,
-- which can be found at https://sellaroli.com/apps/nem-translation-tool/
--
---------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------

local t = {}

t[1] = "Det kan jeg ikke gjøre."  -- {TEXT, input.moon}
t[2] = "Det går ikke."  -- {TEXT, input.moon}
t[3] = "Næ."  -- {TEXT, input.moon}
t[4] = "Kanskje senere."  -- {TEXT, input.moon}
t[5] = "valg"  -- {TEXT, ui/cursor.moon}
t[6] = "Det store intet, overalt."  -- {LOOK, rooms/present.moon}
t[8] = "Nå har han i det minste en grunn til å ikke se på veien."  -- {LOOK, rooms/present.moon}
t[9] = "onkel Lee"  -- {TEXT, rooms/present.moon}
t[10] = "Her var det."  -- {INES, rooms/present.moon}
t[11] = "Jeg håper dette virker, for din egen del."  -- {INES, rooms/present.moon}
t[12] = "Jeg har ikke lyst til å sitte fast i en tidstunell"  -- {INES, rooms/present.moon}
t[357] = "Ikke noe å bry seg om, vi er straks tilbake i vår egen tidslinje."  -- {LEE, rooms/present.moon}
t[13] = "Det burde jeg ha forventet."  -- {INES, rooms/present.moon}
t[14] = "Det er ingen vits, det var den ødelagte han ga meg."  -- {INES, rooms/present.moon}
t[15] = "Hvorfor, onkel Lee, hvorfor?"  -- {LOOK, rooms/present.moon}
t[16] = "tidsnavigator"  -- {TEXT, rooms/present.moon}
t[17] = "Det ser ut som en mobiltelefon."  -- {INES, rooms/present.moon}
t[18] = "Har han skapt en tidsmaskin ut av en telefon?!"  -- {INES, rooms/present.moon}
t[19] = "Det finnes noen tidsperioder på speed dial."  -- {INES, rooms/present.moon}
t[20] = "plante"  -- {TEXT, rooms/present.moon}
t[21] = "Hvorfor har onkel Lee en plante i en varebil?"  -- {LOOK, rooms/present.moon}
t[22] = "Det er noe skjult i potta!"  -- {INES, rooms/present.moon}
t[23] = "Det er en reserveenhet."  -- {INES, rooms/present.moon}
t[24] = "Hvordan havnet det der?"  -- {INES, rooms/present.moon}
t[25] = "Jeg fant apparatet i denne potta tidligere."  -- {INES, rooms/present.moon}
t[26] = "Jeg tror ikke det ville hjelpe å legge det tilbake nå."  -- {INES, rooms/present.moon}
t[27] = "Men jeg føler at jeg er på rett spor."  -- {INES, rooms/present.moon}
t[62] = "Hun stirrer veldig intenst på den plakaten."  -- {LOOK, rooms/collector.moon}
t[63] = "Hun stirrer veldig intenst på meg."  -- {LOOK, rooms/collector.moon}
t[64] = "Hun lytter veldig intenst på demo-tapen."  -- {LOOK, rooms/collector.moon}
t[65] = "?"  -- {TEXT, rooms/collector.moon}
t[66] = "samler"  -- {TEXT, rooms/collector.moon}
t[67] = "Vær så god."  -- {INES, rooms/collector.moon}
t[371] = "Er dette...?"  -- {COLLECTOR, rooms/collector.moon}
t[372] = "...er dette hva jeg tror det er?"  -- {COLLECTOR, rooms/collector.moon}
t[68] = "Jepp."  -- {INES, rooms/collector.moon}
t[373] = "Det ser ekte ut!"  -- {COLLECTOR, rooms/collector.moon}
t[374] = "Jeg kan ikke tro det!"  -- {COLLECTOR, rooms/collector.moon}
t[375] = "Jeg må høre på den med en gang for å bli sikker."   -- {COLLECTOR, rooms/collector.moon}
t[376] = "Vær så snill å ikke røre noe mens jeg er distrahert."  -- {COLLECTOR, rooms/collector.moon}
t[69] = "Vær så god."  -- {INES, rooms/collector.moon}
t[377] = "Hva er dette?"  -- {COLLECTOR, rooms/collector.moon}
t[70] = "Det er en demo-tape fra bandet som pleide å eie denne varebilen."  -- {INES, rooms/collector.moon}
t[71] = "Det er demo-tapen som du så gjerne ville ha."  -- {INES, rooms/collector.moon}
t[378] = "Umulig, denne kassetten ser helt ny ut."  -- {COLLECTOR, rooms/collector.moon}
t[379] = "Skal du få meg til å tro at den er fra sekstitallet?"  -- {COLLECTOR, rooms/collector.moon}
t[72] = "Men den ER det, jeg lover!"  -- {INES, rooms/collector.moon}
t[380] = "Veldig troverdig historie, framtidsjente."  -- {COLLECTOR, rooms/collector.moon}
t[381] = "Dette søppelet kan du beholde selv."  -- {COLLECTOR, rooms/collector.moon}
t[73] = "Jeg har allerede prøvd, hun tror ikke at det er ekte."  -- {INES, rooms/collector.moon}
t[74] = "Den ser ikke gammel nok ut."  -- {INES, rooms/collector.moon}
t[75] = "Mistenkelig."  -- {LOOK, rooms/collector.moon}
t[76] = "plekter"  -- {TEXT, rooms/collector.moon}
t[77] = "De festet faktisk selve plekteret på plakaten."  -- {INES, rooms/collector.moon}
t[78] = "En helt vanlig ting å finne på."  -- {INES, rooms/collector.moon}
t[79] = "Snodig positur. Komposisjonen leder blikket til plekteret."  -- {LOOK, rooms/collector.moon}
t[80] = "Forut for sin tid. Øh, var den ikke annerledes før?"  -- {LOOK, rooms/collector.moon}
t[81] = "plakat"  -- {TEXT, rooms/collector.moon}
t[82] = "Hah, plekterer som gitaristen holder ser ikke helt flat ut."  -- {INES, rooms/collector.moon}
t[83] = "Dette er det kunstnere ville kalle \"i relieff\"."  -- {INES, rooms/collector.moon}
t[84] = "En gammeldags båndopptaker. Jeg må ha den."  -- {LOOK, rooms/collector.moon}
t[85] = "båndopptaker"  -- {TEXT, rooms/collector.moon}
t[382] = "Ikke rør det!"  -- {COLLECTOR, rooms/collector.moon}
t[383] = "Det er uerstattelig."  -- {COLLECTOR, rooms/collector.moon}
t[86] = "Fanken."  -- {INES, rooms/collector.moon}
t[87] = "He he."  -- {INES, rooms/collector.moon}
t[384] = "Å, det er deg igjen."  -- {COLLECTOR, rooms/collector.moon}
t[385] = "HOI!"  -- {COLLECTOR, rooms/collector.moon}
t[386] = "Kom deg vekk derfra!"  -- {COLLECTOR, rooms/collector.moon}
t[387] = "Jeg vil ikke ha deg i nærheten av min enestående plakat."  -- {COLLECTOR, rooms/collector.moon}
t[88] = "plante"  -- {TEXT, rooms/collector.moon}
t[89] = "Er denne den samme planten som onkel Lee har i varebilen sin?"  -- {LOOK, rooms/collector.moon}
t[90] = "Skal vi se..."  -- {INES, rooms/collector.moon}
t[91] = "...Jeg fant jo det fungerende apparatet som jeg ga til onkel Lee i blomsterpotta."  -- {INES, rooms/collector.moon}
t[92] = "Som jeg tipper at faktisk var akkurat det samme apparatet jeg har nå."  -- {INES, rooms/collector.moon}
t[93] = "Så jeg må nok legge det her for å fikse paradokset sånn at fortids-jeg kan finne det i framtiden."  -- {INES, rooms/collector.moon}
t[94] = "Som egentlig er nået."  -- {INES, rooms/collector.moon}
t[95] = "...du verden."  -- {INES, rooms/collector.moon}
t[96] = "Tidsreiser er noe TRIPPY greier."  -- {INES, rooms/collector.moon}
t[97] = "Jeg skal legge apparatet inn i potta og så trykke på knappen derfra."  -- {INES, rooms/collector.moon}
t[98] = "bøker"  -- {TEXT, rooms/collector.moon}
t[99] = "De er alle eksemplarer av samme bok: \"Bandet som manglet trommer\"."  -- {LOOK, rooms/collector.moon}
t[100] = "CD-er"  -- {TEXT, rooms/collector.moon}
t[101] = "De ser nyere ut enn resten av tingene her inne."  -- {LOOK, rooms/collector.moon}
t[102] = "LP-er"  -- {TEXT, rooms/collector.moon}
t[103] = "En haug med vinylskiver. Ja, jeg er gammel nok til å vite hva de er."  -- {LOOK, rooms/collector.moon}
t[104] = "stereoanlegg"  -- {TEXT, rooms/collector.moon}
t[105] = "State-of-the-art. Eller det ville i hvert fall vært det for noen tiår siden."  -- {LOOK, rooms/collector.moon}
t[28] = "Jeg når ikke dit, kraftfeltet er i veien."  -- {INES, rooms/future.moon}
t[29] = "Det eneste gullet i spillet."  -- {LOOK, rooms/future.moon}
t[30] = "Det ser kjent ut."  -- {LOOK, rooms/future.moon}
t[31] = "mynt"  -- {TEXT, rooms/future.moon}
t[32] = "Jeg trodde ikke det var noe gull i dette spillet!"  -- {INES, rooms/future.moon}
t[33] = "Å, det er bare forgyllet."  -- {INES, rooms/future.moon}
t[34] = "Jeg håper ikke dette skaper problemer i framtiden."  -- {INES, rooms/future.moon}
t[35] = "Et skilt med en beskrivelse av mynten."  -- {LOOK, rooms/future.moon}
t[36] = "skilt"  -- {TEXT, rooms/future.moon}
t[37] = "Det står at det er en reproduksjon av den første mynten som onkel Lee tjente inn."  -- {INES, rooms/future.moon}
t[38] = "Det virker som den originale gikk tapt da jeg var barn."  -- {INES, rooms/future.moon}
t[39] = "He he."  -- {INES, rooms/future.moon}
t[40] = "Hva har han gjort denne gangen?"  -- {LOOK, rooms/future.moon}
t[41] = "Han overrasker meg alltid på en eller annen måte."   -- {LOOK, rooms/future.moon}
t[42] = "onkel Lee?"  -- {TEXT, rooms/future.moon}
t[43] = "hoLeegram"  -- {TEXT, rooms/future.moon}
t[44] = "Onkel Lee?"  -- {INES, rooms/future.moon}
t[45] = "Han kan ikke høre meg fra denne siden av kraftfeltet."  -- {INES, rooms/future.moon}
t[46] = "En vakker luke. Det kan du ikke se på grunn av oppløsningen, men den er virkelig forseggjort."  -- {LOOK, rooms/future.moon}
t[47] = "åpning"  -- {TEXT, rooms/future.moon}
t[48] = "Det får jeg ikke til herfra."  -- {INES, rooms/future.moon}
t[49] = "Her har du en av tingene du trengte."  -- {INES, rooms/future.moon}
t[50] = "Her er den andre tingen du trengte."  -- {INES, rooms/future.moon}
t[358] = "Namnam!"  -- {HOLEEGRAM, rooms/future.moon}
t[51] = "...hva?"  -- {INES, rooms/future.moon}
t[359] = "Jeg sa ikke noe."  -- {HOLEEGRAM, rooms/future.moon}
t[52] = "Glem det, kan du fikse denne dingsen eller ikke?"  -- {INES, rooms/future.moon}
t[360] = "Jobber med saken."  -- {HOLEEGRAM, rooms/future.moon}
t[361] = "biip bopp."  -- {HOLEEGRAM, rooms/future.moon}
t[362] = "Bzzzzzzzzzzz."  -- {HOLEEGRAM, rooms/future.moon}
t[363] = "Værsågod."  -- {HOLEEGRAM, rooms/future.moon}
t[53] = "Hvorfor skulle jeg gjøre det?"  -- {INES, rooms/future.moon}
t[54] = "De sitter veldig stille. Det kan ikke være særlig behagelig."  -- {LOOK, rooms/past.moon}
t[55] = "musikere med tvilsomme holdninger"  -- {TEXT, rooms/past.moon}
t[56] = "Hvorfor skulle jeg gjøre det?"  -- {INES, rooms/past.moon}
t[57] = "Er det dette plekteret du lette etter?"  -- {INES, rooms/past.moon}
t[364] = "Plekteret mitt!"  -- {PEPPE, rooms/past.moon}
t[365] = "Det fine plekteret mitt!"  -- {PEPPE, rooms/past.moon}
t[366] = "Vi savna deg så mye, lille venn!"  -- {PAOLO, rooms/past.moon}
t[367] = "Ikke skremme oss sånn igjen!"  -- {ANDREA, rooms/past.moon}
t[58] = "Nå – kan jeg få gitaren din?"  -- {INES, rooms/past.moon}
t[368] = "Javisst, jeg skal hente en fra lageret."  -- {PEPPE, rooms/past.moon}
t[369] = "Det gjorde vondt."  -- {PEPPE, rooms/past.moon}
t[370] = "Dette ga meg en idé til et platecover."  -- {PAOLO, rooms/past.moon}
t[59] = "Jeg skal sette den på hvis vi snakker om noe interessant."  -- {INES, rooms/past.moon}
t[60] = "Den ser ikke ut som den planten onkel Lee har."  -- {LOOK, rooms/past.moon}
t[61] = "mistenkelig plante"  -- {TEXT, rooms/past.moon}
t[106] = "Jeg har aldri sett noen bruke en slik til å ha hansker i."  -- {LOOK, rooms/common.moon}
t[107] = "hanskerom"  -- {TEXT, rooms/common.moon}
t[108] = "Det er tomt."  -- {INES, rooms/common.moon}
t[109] = "Jeg tar ut tapen."  -- {INES, rooms/common.moon}
t[110] = "Akkurat moden nok."  -- {INES, rooms/common.moon}
t[111] = "Det var enda godt at ingen brukte hanskerommet i alle disse årene."  -- {INES, rooms/common.moon}
t[112] = "Jeg legger det inni."  -- {INES, rooms/common.moon}
t[113] = "Det trengs ikke, jeg har allerede foreldet den."  -- {INES, rooms/common.moon}
t[114] = "tidsnavigator"  -- {TEXT, inventory.moon}
t[115] = "Det er tidsmaskinen som startet alt dette rotet."  -- {LOOK, inventory.moon}
t[116] = "mynt"  -- {TEXT, inventory.moon}
t[117] = "Jeg lurer på om det er sjokolade inni."  -- {LOOK, inventory.moon}
t[118] = "virkelighetsfiksemaskin™"  -- {TEXT, inventory.moon}
t[119] = "HVEM la den inn i potta, og HVORFOR?"  -- {LOOK, inventory.moon}
t[120] = "virkelighetsfiksemaskin™ (forhåpentligvis fungerende)"  -- {TEXT, inventory.moon}
t[121] = "Fikset og klar til bruk."  -- {LOOK, inventory.moon}
t[122] = "Det skal visst ikke være så lett, selvsagt."  -- {LOOK, inventory.moon}
t[123] = "La oss se om denne dingsen faktisk virker."  -- {INES, inventory.moon}
t[633] = "Vent nå litt!"  -- {PRESIDENT_INES, inventory.moon}
t[124] = "...hva!?"  -- {INES, inventory.moon}
t[125] = "Hvem er du?"  -- {INES, inventory.moon}
t[634] = "Jasså."  -- {PRESIDENT_INES, inventory.moon}
t[635] = "Slapp av, jeg er deg, fra framtiden."  -- {PRESIDENT_INES, inventory.moon}
t[388] = "Hei, Ines!"  -- {HOLEEGRAM, inventory.moon}
t[389] = "Oj!"  -- {ANDREA, inventory.moon}
t[126] = "Å fy f---"  -- {INES, inventory.moon}
t[636] = "Har ikke tid til noe tull."  -- {PRESIDENT_INES, inventory.moon}
t[637] = "Jeg har viktige ting å gjøre."  -- {PRESIDENT_INES, inventory.moon}
t[638] = "Jeg er PRESIDENTEN."  -- {PRESIDENT_INES, inventory.moon}
t[127] = "Det er skikkelig ku--"  -- {INES, inventory.moon}
t[639] = "Hva sa jeg nettopp?"  -- {PRESIDENT_INES, inventory.moon}
t[128] = "Beklager, frue."  -- {INES, inventory.moon}
t[640] = "Jeg kom hit for å hindre deg i å ødelegge tid- og romskontinuum."  -- {PRESIDENT_INES, inventory.moon}
t[641] = "Hvis du trykker på knappen nå, vil du skape et tidsparadoks."  -- {PRESIDENT_INES, inventory.moon}
t[642] = "Du trenger å løse paradokset før du tar i bruk apparatet."  -- {PRESIDENT_INES, inventory.moon}
t[129] = "Kan du si meg hvordan?"  -- {INES, inventory.moon}
t[643] = "Jeg skulle ønske jeg kunne, men da jeg var – bokstavelig talt – i dine sko, fortalte ikke framtids-Ines hvordan."  -- {PRESIDENT_INES, inventory.moon}
t[644] = "Så, hvis jeg sier det nå, vil det skape enda et paradoks."  -- {PRESIDENT_INES, inventory.moon}
t[130] = "Søren."  -- {INES, inventory.moon}
t[645] = "Det var det jeg sa også."  -- {PRESIDENT_INES, inventory.moon}
t[646] = "Vel, da er det i dine hender."  -- {PRESIDENT_INES, inventory.moon}
t[647] = "Plikten kaller."  -- {PRESIDENT_INES, inventory.moon}
t[390] = "Ha det, Ines!"  -- {HOLEEGRAM, inventory.moon}
t[131] = "virkelighetsfiksemaskin™ (ødelagt)"  -- {TEXT, inventory.moon}
t[132] = "Billig onkel Lee-skrap."  -- {LOOK, inventory.moon}
t[133] = "plekter til gitar"  -- {TEXT, inventory.moon}
t[134] = "Er dette blod?"  -- {LOOK, inventory.moon}
t[135] = "båndopptaker"  -- {TEXT, inventory.moon}
t[136] = "Den har en tape inni allerede. Det var jo praktisk."  -- {LOOK, inventory.moon}
t[137] = "el-gitar"  -- {TEXT, inventory.moon}
t[138] = "tape"  -- {TEXT, inventory.moon}
t[139] = "Jeg lurer på om dette er lovlig."  -- {LOOK, inventory.moon}
t[140] = "\"vintage\" tape"  -- {TEXT, inventory.moon}
t[141] = "Jeg lurer på om den har blitt noe bedre av å eldes."  -- {LOOK, inventory.moon}
t[142] = "magnetisk pickup"  -- {TEXT, inventory.moon}
t[143] = "Det var ganske tilfredstillende å røske ut denne fra gitaren."  -- {LOOK, inventory.moon}
t[144] = "Onkel Lee, er du sikker på at du ikke vil at jeg skal kjøre i stedet?"  -- {INES, dialogues/lee.moon}
t[391] = "Det går bra, jenta mi! Bare sitt og kos deg med utsikten"   -- {LEE, dialogues/lee.moon}
t[145] = "Jeg ville kost meg mer hvis du holdt blikket på motorveien."  -- {INES, dialogues/lee.moon}
t[392] = "Jeg har sett den mange ganger, det er ikke noe spesielt med den."  -- {LEE, dialogues/lee.moon}
t[146] = "*Sukk* Er du sikker på at du er på rett vei, i det miste?"  -- {INES, dialogues/lee.moon}
t[393] = "Jo men klart det! Jeg kunne ha kjørt oss til Fenfef-vannet med bind for øynene!"  -- {LEE, dialogues/lee.moon}
t[147] = "Det ville ikke vært veldig forskjellig fra det du gjør nå."  -- {INES, dialogues/lee.moon}
t[148] = "...har vi ikke vært inni denne tunellen ganske lenge nå?"  -- {INES, dialogues/lee.moon}
t[394] = "Du vet hvordan det er, disse tunellene virker UENDELIG lange!"  -- {LEE, dialogues/lee.moon}
t[149] = "Onkel Lee."  -- {INES, dialogues/lee.moon}
t[395] = "Oisann."  -- {LEE, dialogues/lee.moon}
t[150] = "ONKEL LEE."  -- {INES, dialogues/lee.moon}
t[396] = "Jeg må ha satt på tidsnavigatoren."  -- {LEE, dialogues/lee.moon}
t[397] = "Det var sikkert derfor jeg ikke klarte å finne den noe sted."  -- {LEE, dialogues/lee.moon}
t[151] = "TIDSNAVIGATOR?!"  -- {INES, dialogues/lee.moon}
t[398] = "Det er ikke noe å bry seg om."  -- {LEE, dialogues/lee.moon}
t[399] = "Jeg har alltid med meg virkelighetsfiksemaskinen™ nettopp for sånne situasjoner."  -- {LEE, dialogues/lee.moon}
t[400] = "Å. Tror den er ødelagt."   -- {LEE, dialogues/lee.moon}
t[152] = "Ookei. Supert."  -- {INES, dialogues/lee.moon}
t[401] = "Det burde være en reserveenhet her et sted."  -- {LEE, dialogues/lee.moon}
t[402] = "Men behold denne også."  -- {LEE, dialogues/lee.moon}
t[153] = "Onkel Lee?"  -- {INES, dialogues/lee.moon}
t[403] = "Ja, jenta mi?"  -- {LEE, dialogues/lee.moon}
t[154] = "Hvor burde jeg lete etter reserveenheten?"  -- {ECHO, dialogues/lee.moon}
t[155] = "Hva er denne tidsnavigatoren, egentlig?"  -- {ECHO, dialogues/lee.moon}
t[156] = "Denne varebilen ser mye større ut enn den burde."  -- {ECHO, dialogues/lee.moon}
t[157] = "Ok, hadet."  -- {ECHO, dialogues/lee.moon}
t[404] = "Ha det!"  -- {LEE, dialogues/lee.moon}
t[405] = "Det vet jeg ikke."  -- {LEE, dialogues/lee.moon}
t[406] = "Hvor ville DU ha lagt den?"  -- {LEE, dialogues/lee.moon}
t[158] = "JEG?!"  -- {INES, dialogues/lee.moon}
t[159] = "Det var du som mistet den!"  -- {INES, dialogues/lee.moon}
t[407] = "Etter sigende."  -- {LEE, dialogues/lee.moon}
t[408] = "Det er min siste og beste oppfinnelse!"  -- {LEE, dialogues/lee.moon}
t[409] = "Den er så ny at jeg ikke har rukket å legge til ™ til navnet ennå!"   -- {LEE, dialogues/lee.moon}
t[160] = "Så hva brukes den til?"  -- {ECHO, dialogues/lee.moon}
t[161] = "Minn meg på hva den gjør."  -- {ECHO, dialogues/lee.moon}
t[162] = "Hvorfor lagde du noe sånt i det hele tatt?"  -- {ECHO, dialogues/lee.moon}
t[163] = "Kan du minne meg på hvorfor du lagde den?"  -- {ECHO, dialogues/lee.moon}
t[164] = "Glem det."  -- {ECHO, dialogues/lee.moon}
t[410] = "For et dumt spørsmål!"  -- {LEE, dialogues/lee.moon}
t[411] = "Det er et apparat til å navigere gjennom tida."  -- {LEE, dialogues/lee.moon}
t[412] = "Navnet sier jo det tydelig."  -- {LEE, dialogues/lee.moon}
t[165] = "Er ikke det farlig?"  -- {INES, dialogues/lee.moon}
t[413] = "Ikke hvis du vet hva du driver med."  -- {LEE, dialogues/lee.moon}
t[166] = "Og vet DU hva du driver med?"  -- {INES, dialogues/lee.moon}
t[414] = "Sånn cirka."  -- {LEE, dialogues/lee.moon}
t[415] = "Det er et apparat til å navigere gjennom tid."  -- {LEE, dialogues/lee.moon}
t[416] = "Ja, jeg drev og lagde middag her om dagen da jeg la merke til at jeg var tom for gafler."  -- {LEE, dialogues/lee.moon}
t[167] = "Du burde ikke bruke engangsservise, onkel Lee!"  -- {INES, dialogues/lee.moon}
t[168] = "Det er dårlig for miljøet!"  -- {INES, dialogues/lee.moon}
t[417] = "Alle gaflene mine kan brukes flere ganger, det skulle bare mangle."  -- {LEE, dialogues/lee.moon}
t[169] = "Men du gikk tom for gafler likevel?"  -- {INES, dialogues/lee.moon}
t[418] = "Ja."  -- {LEE, dialogues/lee.moon}
t[419] = "Uansett – jeg kom på at jeg hadde fremdeles noen igjen dagen før."  -- {LEE, dialogues/lee.moon}
t[420] = "Så jeg bestemte meg for å lage en tidmaskin for å gå tilbake i tid og hente dem."  -- {LEE, dialogues/lee.moon}
t[421] = "Når jeg tenker meg om, det er sikkert derfor jeg gikk tom til å begynne med."  -- {LEE, dialogues/lee.moon}
t[422] = "For å reise tilbake i tid og stjele noen gafler."  -- {LEE, dialogues/lee.moon}
t[423] = "Fra meg selv."  -- {LEE, dialogues/lee.moon}
t[170] = "Okei."  -- {INES, dialogues/lee.moon}
t[424] = "Skaperne prøvde å tegne den i realistisk størrelse, men det funket ikke helt."  -- {LEE, dialogues/lee.moon}
t[171] = "...hva?"  -- {INES, dialogues/lee.moon}
t[425] = "Øh, jeg mener, det er såklart fordi det er en spesialmodell. Den ble bygd spesielt for et rockeband på sekstitallet."  -- {LEE, dialogues/lee.moon}
t[172] = "Hvordan fikk du tak i den?"  -- {INES, dialogues/lee.moon}
t[426] = "Jeg fikk den av en samler."  -- {LEE, dialogues/lee.moon}
t[173] = "Den må ha kostet en formue!"  -- {INES, dialogues/lee.moon}
t[427] = "Kostet?"  -- {LEE, dialogues/lee.moon}
t[174] = "Onkel Lee! Stjal du den?"  -- {INES, dialogues/lee.moon}
t[428] = "Jeg vant den, det var bare rett og rimelig."  -- {LEE, dialogues/lee.moon}
t[429] = "Ikke min feil at hun ikke kunne spille vri åtteren."  -- {LEE, dialogues/lee.moon}
t[430] = "Den er spesialbygd for et rockeband fra sekstitallet."  -- {LEE, dialogues/lee.moon}
t[431] = "Jeg fikk den av en samler."  -- {LEE, dialogues/lee.moon}
t[175] = "Hallo."  -- {INES, dialogues/wilson.moon}
t[176] = "Det er ingenting verdt å ta opp."  -- {INES, dialogues/wilson.moon}
t[177] = "Denne gjengen er ganske kjedelig."  -- {INES, dialogues/wilson.moon}
t[178] = "Der borte."  -- {INES, dialogues/wilson.moon}
t[179] = "Lurer på om denne tapen vil bli verdt noe en dag."  -- {INES, dialogues/wilson.moon}
t[432] = "Gutta, dere kommer'ke til å tru hva jeg ser nå!"  -- {PAOLO, dialogues/wilson.moon}
t[433] = "Det er ei jente der, hu ser ikke noe glad ut og har GRØNT hår!"  -- {PAOLO, dialogues/wilson.moon}
t[434] = "Hu ser DØDSSINNA ut."  -- {PAOLO, dialogues/wilson.moon}
t[435] = "Dust, vi ser henne alle sammen."  -- {ANDREA, dialogues/wilson.moon}
t[436] = "Det må være enda ei tidsvandrar."  -- {PEPPE, dialogues/wilson.moon}
t[437] = "Sjuukt."  -- {PAOLO, dialogues/wilson.moon}
t[180] = "Såh, dere er et band?"  -- {ECHO, dialogues/wilson.moon}
t[438] = "Hva er det som avslørte oss?"  -- {ANDREA, dialogues/wilson.moon}
t[181] = "Hallo! Gitarene."  -- {ECHO, dialogues/wilson.moon}
t[439] = "Hvoffor va'kke trommer et av de fire valgene ‘a?"  -- {PAOLO, dialogues/wilson.moon}
t[182] = "De rufsete men gjennomtenkte hårsveisene hårstilene og den rebelske attityden."  -- {ECHO, dialogues/wilson.moon}
t[440] = "Sjå på deg sjølv!"  -- {PEPPE, dialogues/wilson.moon}
t[183] = "Intuisjon."  -- {ECHO, dialogues/wilson.moon}
t[441] = "Særlig."  -- {ANDREA, dialogues/wilson.moon}
t[184] = "Det dukker opp et skilt når jeg flytter musepekeren over dere."  -- {ECHO, dialogues/wilson.moon}
t[442] = "Det bekrefter teknisk sett ikke at vi er et band."  -- {PEPPE, dialogues/wilson.moon}
t[185] = "Så dere er ikke det?"  -- {INES, dialogues/wilson.moon}
t[443] = "...joda."  -- {PEPPE, dialogues/wilson.moon}
t[186] = "Fortell om bandet..."  -- {ECHO, dialogues/wilson.moon}
t[187] = "Jeg leter etter en ting."  -- {ECHO, dialogues/wilson.moon}
t[188] = "Det var alt."  -- {ECHO, dialogues/wilson.moon}
t[444] = "Ha det bra."  -- {ANDREA, dialogues/wilson.moon}
t[445] = "Jeg stoler ikke på deg ass, grønnhåra synet."  -- {PAOLO, dialogues/wilson.moon}
t[446] = "Ver så god å bli i hula vår og sjå deg ikring om du har lyst."  -- {PEPPE, dialogues/wilson.moon}
t[189] = "Er bilen også øvingslokalet deres?"  -- {ECHO, dialogues/wilson.moon}
t[447] = "Ja, vi fikk den spesialbygd."  -- {PAOLO, dialogues/wilson.moon}
t[448] = "Vi sover her også."  -- {ANDREA, dialogues/wilson.moon}
t[190] = "En kreativ løsning."  -- {INES, dialogues/wilson.moon}
t[449] = "Vi måtte selje heimane våre for å få råd."  -- {PEPPE, dialogues/wilson.moon}
t[450] = "Og trommene mine."  -- {PAOLO, dialogues/wilson.moon}
t[451] = "Men vi angrer ikke."  -- {ANDREA, dialogues/wilson.moon}
t[452] = "Beste avgjørelse vi har tatt noensinne."  -- {PEPPE, dialogues/wilson.moon}
t[191] = "Savner ikke dere et trommesett?"  -- {ECHO, dialogues/wilson.moon}
t[453] = "Jo."  -- {PAOLO, dialogues/wilson.moon}
t[192] = "...er ikke det et problem?"  -- {INES, dialogues/wilson.moon}
t[454] = "Nei."  -- {PAOLO, dialogues/wilson.moon}
t[193] = "Jobber dere med noen låt for tida?"  -- {ECHO, dialogues/wilson.moon}
t[455] = "Jo, faktisk."  -- {PEPPE, dialogues/wilson.moon}
t[456] = "Den beste hittil."  -- {ANDREA, dialogues/wilson.moon}
t[457] = "Vi kan spelle den for deg."  -- {PAOLO, dialogues/wilson.moon}
t[194] = "Jeg burde nok ta den opp."  -- {INES, dialogues/wilson.moon}
t[195] = "Det er ikke nødvendig--"  -- {INES, dialogues/wilson.moon}
t[196] = "Det var relativt smertefritt."  -- {INES, dialogues/wilson.moon}
t[458] = "Hoj, det hadde vært en fet tittel til en skive."  -- {PAOLO, dialogues/wilson.moon}
t[197] = "Nok om dere."  -- {ECHO, dialogues/wilson.moon}
t[459] = "Vi har gått tom."  -- {PAOLO, dialogues/wilson.moon}
t[460] = "Og før du spør..."  -- {ANDREA, dialogues/wilson.moon}
t[461] = "...den der bakerst er for privat bruk."   -- {PEPPE, dialogues/wilson.moon}
t[198] = "Hva?!"  -- {INES, dialogues/wilson.moon}
t[199] = "Det var ikke det jeg mente."  -- {INES, dialogues/wilson.moon}
t[200] = "Hvorfor gikk du utifra det?"  -- {INES, dialogues/wilson.moon}
t[462] = "Vel, det er det fyren med bart vanligvis er ute etter."  -- {ANDREA, dialogues/wilson.moon}
t[463] = "Artig type."  -- {PAOLO, dialogues/wilson.moon}
t[201] = "...selvsagt."  -- {INES, dialogues/wilson.moon}
t[202] = "Dere har ikke tilfeldigvis noe gull gjemt her en plass?"  -- {ECHO, dialogues/wilson.moon}
t[464] = "Du er ikke den første som spør om det i dag."  -- {PAOLO, dialogues/wilson.moon}
t[465] = "Jeg var først."  -- {PEPPE, dialogues/wilson.moon}
t[466] = "Og jeg rett etterpå."  -- {ANDREA, dialogues/wilson.moon}
t[467] = "Uansett, det er ingen gull i dette spillet."  -- {PAOLO, dialogues/wilson.moon}
t[203] = "Søren."  -- {INES, dialogues/wilson.moon}
t[204] = "En magnet. Jeg trenger en magnet."  -- {ECHO, dialogues/wilson.moon}
t[205] = "Har dere en?"  -- {INES, dialogues/wilson.moon}
t[468] = "Jeg tror ikke det."  -- {PEPPE, dialogues/wilson.moon}
t[469] = "Usansynnlig."  -- {ANDREA, dialogues/wilson.moon}
t[470] = "Jeg ville sagt det er en ganske liten sjanse."  -- {PAOLO, dialogues/wilson.moon}
t[206] = "Søren."  -- {INES, dialogues/wilson.moon}
t[207] = "Er dere HELT sikre på at dere ikke har noen magneter?"  -- {ECHO, dialogues/wilson.moon}
t[471] = "Rimelig sikre."  -- {ANDREA, dialogues/wilson.moon}
t[472] = "Vi har ingen grunn til å juge."  -- {PEPPE, dialogues/wilson.moon}
t[473] = "Snakk for deg selv."  -- {PAOLO, dialogues/wilson.moon}
t[208] = "Javel, jeg har blitt fortalt at el-gitarer inneholder magneter."  -- {INES, dialogues/wilson.moon}
t[474] = "Har gitarer magneter i?!."  -- {PAOLO, dialogues/wilson.moon}
t[475] = "Oj!"  -- {ANDREA, dialogues/wilson.moon}
t[476] = "Du, det er skikkelig kult!"  -- {PEPPE, dialogues/wilson.moon}
t[477] = "Da har vi sikkert magneter, da."  -- {PEPPE, dialogues/wilson.moon}
t[209] = "Kan jeg låne en av gitarene deres?"  -- {ECHO, dialogues/wilson.moon}
t[478] = "Jada, hvorfor ik--"  -- {PAOLO, dialogues/wilson.moon}
t[479] = "Ikke snakk om!"  -- {ANDREA, dialogues/wilson.moon}
t[480] = "Vi trenger dem."  -- {PEPPE, dialogues/wilson.moon}
t[481] = "Vi er jo et band, vet du."  -- {ANDREA, dialogues/wilson.moon}
t[210] = "Har dere ingen reservegitarer?"  -- {INES, dialogues/wilson.moon}
t[482] = "Vel, når jeg tenker på det nå..."  -- {PEPPE, dialogues/wilson.moon}
t[483] = "...vi har mer enn nok på lageret."  -- {ANDREA, dialogues/wilson.moon}
t[211] = "Kan jeg få lånt en, da?"  -- {INES, dialogues/wilson.moon}
t[484] = "Nei."  -- {PEPPE, dialogues/wilson.moon}
t[212] = "Er det noe jeg kan gjøre for å overtale dere til å låne meg en gitar?"  -- {ECHO, dialogues/wilson.moon}
t[485] = "Nope."  -- {PEPPE, dialogues/wilson.moon}
t[486] = "Ikke sjans i havet."  -- {ANDREA, dialogues/wilson.moon}
t[487] = "Gutta, hva om..."  -- {PAOLO, dialogues/wilson.moon}
t[488] = "...PLEKTERET?"  -- {PAOLO, dialogues/wilson.moon}
t[489] = "Jaha?."  -- {PEPPE, dialogues/wilson.moon}
t[490] = "SELVESTE PLEKTERET."  -- {PEPPE, dialogues/wilson.moon}
t[213] = "Plekteret?"  -- {INES, dialogues/wilson.moon}
t[491] = "Jeg pleide å ha et plekter en gang i tida."  -- {PEPPE, dialogues/wilson.moon}
t[492] = "Det var et virkelig pålitelig, flott plekter."  -- {PEPPE, dialogues/wilson.moon}
t[493] = "Det lyttet alltid, uten å dømme."  -- {PEPPE, dialogues/wilson.moon}
t[494] = "Det lo av alle vitsene mine."  -- {PAOLO, dialogues/wilson.moon}
t[495] = "Der var nesten som det fjerde medlemmet i bandet."  -- {ANDREA, dialogues/wilson.moon}
t[496] = "Men vi mistet det en gang, mens vi øvde."  -- {PAOLO, dialogues/wilson.moon}
t[497] = "En forferdelig dag."  -- {PEPPE, dialogues/wilson.moon}
t[498] = "Måtte det hvile i fred."  -- {ANDREA, dialogues/wilson.moon}
t[214] = "...Skjønner."  -- {INES, dialogues/wilson.moon}
t[215] = "Ville dere gitt meg en gitar hvis jeg finner plekteret?"  -- {ECHO, dialogues/wilson.moon}
t[499] = "Hvis du finner det tapte favorittplekteret, da har vi en avtale."  -- {PEPPE, dialogues/wilson.moon}
t[216] = "Glem det."  -- {ECHO, dialogues/wilson.moon}
t[500] = "Klart det!"  -- {PEPPE, dialogues/wilson.moon}
t[501] = "Det er verdt mer enn noe eller noen i denne bilen!"  -- {PEPPE, dialogues/wilson.moon}
t[502] = "Hoi!"  -- {ANDREA, dialogues/wilson.moon}
t[503] = "Nei, han har rett."  -- {PAOLO, dialogues/wilson.moon}
t[217] = "Noen idé om hvor det kunne befinne seg?"  -- {INES, dialogues/wilson.moon}
t[504] = "Et sted i Woodstock, kanskje."  -- {PEPPE, dialogues/wilson.moon}
t[218] = "Selvfølgelig."  -- {INES, dialogues/wilson.moon}
t[219] = "Samler du på lærjakker?"  -- {ECHO, dialogues/collector.moon}
t[220] = "Samler du på barometere i gull?"  -- {ECHO, dialogues/collector.moon}
t[221] = "Samler du på torturredskaper fra middelalderen?"  -- {ECHO, dialogues/collector.moon}
t[222] = "Samler du på grønnsaker i rare former?"  -- {ECHO, dialogues/collector.moon}
t[223] = "Samler du på angstete og melankolske tenåringsdikt?"  -- {ECHO, dialogues/collector.moon}
t[224] = "Samler du miniatyr- .......?"  -- {ECHO, dialogues/collector.moon}
t[225] = "Samler du DVD-er av TV-serier fra tidlig 2000-tallet?"  -- {ECHO, dialogues/collector.moon}
t[226] = "Samler du weird fiction paperbacks fra femtitallet?"  -- {ECHO, dialogues/collector.moon}
t[227] = "Samler du på klassebildene fra ungdomskolen min?"  -- {ECHO, dialogues/collector.moon}
t[228] = "Puh, det var en lettelse."  -- {INES, dialogues/collector.moon}
t[229] = "Samler du på sportsalmanakker?"  -- {ECHO, dialogues/collector.moon}
t[230] = "Samler du på godteriegg med små leker inni?"  -- {ECHO, dialogues/collector.moon}
t[231] = "Samler du på ?"  -- {ECHO, dialogues/collector.moon}
t[232] = "Samler du på ?"  -- {ECHO, dialogues/collector.moon}
t[233] = "Samler du på ?"  -- {ECHO, dialogues/collector.moon}
t[234] = "Samler du på ?"  -- {ECHO, dialogues/collector.moon}
t[235] = "Samler du på andre samlere?"  -- {ECHO, dialogues/collector.moon}
t[236] = "Hallo."  -- {INES, dialogues/collector.moon}
t[505] = "Du er fortsatt her."  -- {COLLECTOR, dialogues/collector.moon}
t[506] = "HVEM ER DU?!"  -- {COLLECTOR, dialogues/collector.moon}
t[237] = "en... tidsvandrer, antar jeg?"  -- {INES, dialogues/collector.moon}
t[507] = "Ånei, har du noe å gjøre med han merkelige typen med den store barten?"  -- {COLLECTOR, dialogues/collector.moon}
t[238] = "Stopp en halv, bare jeg har lov til å kalle onkel Lee \"merkelig\"."  -- {INES, dialogues/collector.moon}
t[508] = "Samma det."  -- {COLLECTOR, dialogues/collector.moon}
t[509] = "Stikk av."  -- {COLLECTOR, dialogues/collector.moon}
t[510] = "NÅ."  -- {COLLECTOR, dialogues/collector.moon}
t[511] = "Eller ikke rør noe, i det minste."  -- {COLLECTOR, dialogues/collector.moon}
t[239] = "Bilen ser annerledes ut."  -- {ECHO, dialogues/collector.moon}
t[240] = "Hva er alt dette søppelet?"  -- {INES, dialogues/collector.moon}
t[512] = "Søppel?"  -- {COLLECTOR, dialogues/collector.moon}
t[513] = "SØPPEL?"  -- {COLLECTOR, dialogues/collector.moon}
t[514] = "Dette er en eksklusiv og uvurdelig samling!"  -- {COLLECTOR, dialogues/collector.moon}
t[515] = "Du ville ikke forstått det."  -- {COLLECTOR, dialogues/collector.moon}
t[241] = "Er du en samler?"  -- {INES, dialogues/collector.moon}
t[516] = "Jeg er SAMLEREN."  -- {COLLECTOR, dialogues/collector.moon}
t[242] = "Hva slags greier samler du på?"  -- {ECHO, dialogues/collector.moon}
t[517] = "Vær så vennlig å ikke henvise til disse utsøkte gjenstandene med ordet \"greier\" igjen."  -- {COLLECTOR, dialogues/collector.moon}
t[518] = "Jeg spesialiserer meg på gjenstander relatert til eller tidligere eid av BANDET."  -- {COLLECTOR, dialogues/collector.moon}
t[519] = "Jeg har plakater, EP-er, LP-er, CD-remastere (som jeg har produsert selv)..."  -- {COLLECTOR, dialogues/collector.moon}
t[520] = "...til og med disse fire veggene tilhørte en gang BANDET."  -- {COLLECTOR, dialogues/collector.moon}
t[243] = "Mener du bilen? **"  -- {INES, dialogues/collector.moon}
t[521] = "Det er den definitive samlingen."  -- {COLLECTOR, dialogues/collector.moon}
t[522] = "...eller, den ville vært det, hvis jeg bare hadde..."  -- {COLLECTOR, dialogues/collector.moon}
t[244] = "Den er grei, jeg skal dra nå."  -- {ECHO, dialogues/collector.moon}
t[523] = "Ookei. Supert."  -- {COLLECTOR, dialogues/collector.moon}
t[245] = "Har du bandets plekter, det ene som de mistet?"  -- {ECHO, dialogues/collector.moon}
t[524] = "Hvilket mener du?"  -- {COLLECTOR, dialogues/collector.moon}
t[525] = "Aner du hvor mange plektre et band mister i løpet av musikkarrieren sin?"  -- {COLLECTOR, dialogues/collector.moon}
t[526] = "Jeg har hundrevis!"  -- {COLLECTOR, dialogues/collector.moon}
t[246] = "Det... det som var så viktig?"  -- {INES, dialogues/collector.moon}
t[527] = "ALLE er viktige!"  -- {COLLECTOR, dialogues/collector.moon}
t[528] = "De tilhørte BANDET!"  -- {COLLECTOR, dialogues/collector.moon}
t[247] = "...sukk."  -- {INES, dialogues/collector.moon}
t[248] = "Savner du noe i samlingen din?"  -- {ECHO, dialogues/collector.moon}
t[529] = "Sagnet sier at BANDET skrev en prakftull låt."  -- {COLLECTOR, dialogues/collector.moon}
t[530] = "En himmelsk låt som fikk fuglene til å synge med når den ble spilt."  -- {COLLECTOR, dialogues/collector.moon}
t[531] = "Dessverre gikk den tapt."  -- {COLLECTOR, dialogues/collector.moon}
t[532] = "Men ryktene sier at den ble tatt opp en gang."  -- {COLLECTOR, dialogues/collector.moon}
t[533] = "Det skal finnes EN DEMO-TAPE!"  -- {COLLECTOR, dialogues/collector.moon}
t[534] = "...Det hadde vært utrolig å få tak i den."  -- {COLLECTOR, dialogues/collector.moon}
t[249] = "Jeg skjønner."  -- {INES, dialogues/collector.moon}
t[250] = "Samler du tilfeldigvis på gull?"  -- {ECHO, dialogues/collector.moon}
t[535] = "Nei, det finnes ikke noe gull i dette spillet."  -- {COLLECTOR, dialogues/collector.moon}
t[251] = "Søren."  -- {INES, dialogues/collector.moon}
t[252] = "Samler du på magneter, da?"  -- {ECHO, dialogues/collector.moon}
t[536] = "Hva slags galning ville samle på magneter?"  -- {COLLECTOR, dialogues/collector.moon}
t[253] = "...onkel Lee."  -- {INES, dialogues/collector.moon}
t[254] = "Samler du på noe som kan ha magneter INNI?"  -- {INES, dialogues/collector.moon}
t[537] = "Gitarene, antar jeg."  -- {COLLECTOR, dialogues/collector.moon}
t[255] = "Har gitarer magneter i?!."  -- {INES, dialogues/collector.moon}
t[538] = "Klart de har."  -- {COLLECTOR, dialogues/collector.moon}
t[256] = "Kult!"  -- {INES, dialogues/collector.moon}
t[257] = "...Jeg ser ingen gitarer."  -- {INES, dialogues/collector.moon}
t[539] = "De er i lageret."  -- {COLLECTOR, dialogues/collector.moon}
t[540] = "Det er en roterende utstilling."  -- {COLLECTOR, dialogues/collector.moon}
t[258] = "Søren."  -- {INES, dialogues/collector.moon}
t[541] = "Jeg sa det, gitarene har magneter i seg."  -- {COLLECTOR, dialogues/collector.moon}
t[542] = "Men jeg har ingen her."  -- {COLLECTOR, dialogues/collector.moon}
t[543] = "Nei."  -- {COLLECTOR, dialogues/collector.moon}
t[259] = "Kjedelig."  -- {ECHO, dialogues/collector.moon}
t[260] = "Jeg er tilbake."  -- {INES, dialogues/holeegram.moon}
t[544] = "Legg inn apparatet i luken rett under meg, så jeg kan analysere det."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[261] = "...onkel Lee?"  -- {INES, dialogues/holeegram.moon}
t[545] = "Unge Ines! Jeg har ikke sett deg på uendelig lenge!"  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[262] = "...hva skjedde med deg?"  -- {INES, dialogues/holeegram.moon}
t[546] = "Jeg er en hoLeegram!"  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[263] = "Selvfølgelig er du det."  -- {INES, dialogues/holeegram.moon}
t[264] = "Men hvorfor? Skjedde det noe med deg?"  -- {INES, dialogues/holeegram.moon}
t[547] = "Nei nei, jeg ville bare prøve noe nytt."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[548] = "Jeg har ikke følt meg så lett siden jeg var 105!"  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[549] = "Men nok om meg."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[550] = "Jeg antar at du kom deg hit via min vidunderlige tidsnavigator™."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[265] = "Jeg ville ikke kalt den \"vidunderlig\"..."  -- {NOECHO, dialogues/holeegram.moon}
t[266] = "Du er heldig jeg ikke kan slå deg."  -- {NOECHO, dialogues/holeegram.moon}
t[267] = "Jeg er her fordi du LOMMERINGTE med en tidsmaskin."  -- {NOECHO, dialogues/holeegram.moon}
t[268] = "...joda."  -- {INES, dialogues/holeegram.moon}
t[269] = "Hvor langt inn i framtiden er vi nå?"  -- {ECHO, dialogues/holeegram.moon}
t[551] = "Hundrevis av år!"  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[270] = "Kan du hjelpe meg ut av denne tidstunellen?"  -- {ECHO, dialogues/holeegram.moon}
t[552] = "Tidstunell?"  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[271] = "Du trykket på den magiske knappen og forsvant, og jeg ble sittende fast der."  -- {INES, dialogues/holeegram.moon}
t[272] = "Ringer det noen bjeller?"  -- {INES, dialogues/holeegram.moon}
t[553] = "Oisann."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[554] = "Du må nesten spesifisere."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[555] = "Jeg kommer på minst fem tilfeller der det skjedde."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[273] = "Supert."  -- {INES, dialogues/holeegram.moon}
t[274] = "Den første, antar jeg."  -- {INES, dialogues/holeegram.moon}
t[556] = "Ah, turen til Fenfef-vannet!"  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[275] = "Jepp."  -- {INES, dialogues/holeegram.moon}
t[557] = "Da må vi fikse virkelighetsfiksemaskinen™ din, ikke sant?"  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[276] = "Jeg vet ikke, det vet DU."  -- {INES, dialogues/holeegram.moon}
t[558] = "Vi må fikse virkelighetsfiksemaskinen™ din."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[277] = "Hva trengte du igjen for å fikse apparatet?"  -- {ECHO, dialogues/holeegram.moon}
t[559] = "Jeg trenger en MAGNET og MYNTEN fra museet."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[278] = "Skjønner."  -- {INES, dialogues/holeegram.moon}
t[279] = "Ironisk at vi trenger å fikse en virkelighetfiksemaskin."  -- {ECHO, dialogues/holeegram.moon}
t[560] = "Jeg vet."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[561] = "Hvis jeg bare ikke hadde mistet min virkelighetsfiksemaskin-fiksemaskin™."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[280] = "Og hvordan skulle du få fikset en virkelighetsfiksemaskin-fiksemaskin™?"  -- {ECHO, dialogues/holeegram.moon}
t[562] = "Lett! Med hjelp av en virkelighetsfiksemaskin-fiksemaskin-fiksemaskin™."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[563] = "En sånn har jeg faktisk."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[281] = "Søren."  -- {INES, dialogues/holeegram.moon}
t[282] = "Har du noen idé om hvordan jeg kan fikse paradokset som hindrer meg i å bruke maskinen?"  -- {ECHO, dialogues/holeegram.moon}
t[564] = "Selvfølgelig, paradokser er min spesialitet!"  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[565] = "Hvis jeg husker riktig, lagde jeg kun én av disse maskinene."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[283] = "Men jeg husker å ha holdt to stykker av dem samtidig."  -- {INES, dialogues/holeegram.moon}
t[566] = "Ah, da henger paradokset muligens sammen med det."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[284] = "...hmm."  -- {INES, dialogues/holeegram.moon}
t[285] = "Ok, vi ses senere."  -- {ECHO, dialogues/holeegram.moon}
t[567] = "Eller tidligere!"  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[286] = "Hva skjedde med meg i denne tidslinjen?"  -- {ECHO, dialogues/holeegram.moon}
t[568] = "Du er president!"  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[287] = "Herlig!"  -- {INES, dialogues/holeegram.moon}
t[288] = "Vent nå litt, president av hva?"  -- {INES, dialogues/holeegram.moon}
t[569] = "Ja, du er HVAs president."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[289] = "Glem det, bare hjelp meg å komme meg ut av dette rotet."  -- {INES, dialogues/holeegram.moon}
t[290] = "Hva skjedde med kroppen din?"  -- {ECHO, dialogues/holeegram.moon}
t[570] = "Nå skal vi se..."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[571] = "Jeg er litt usikker."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[572] = "Jeg tror jeg liksom glemte den et sted."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[291] = "Hva?!"  -- {INES, dialogues/holeegram.moon}
t[573] = "Det er ikke noe å bekymre seg for, jenta mi."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[574] = "President Ines er på saken, så jeg er sikker på at hun kommer til å finne den før vi vet ordet av det."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[575] = "Framtidens Ines er på saken, så jeg er sikker på at hun kommer til å finne den før vi vet ordet av det."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[292] = "Jo mer jeg får vite om denne tidsperioden, jo mindre jeg vil vite."  -- {INES, dialogues/holeegram.moon}
t[293] = "Hva skjedde med varebilen?"  -- {ECHO, dialogues/holeegram.moon}
t[576] = "Det er \"Onkel Lee-Museet\" nå."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[294] = "Er du berømt nå?!"  -- {INES, dialogues/holeegram.moon}
t[577] = "Egentlig ikke."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[578] = "Jeg er den som skapte museet."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[295] = "Klart du er."  -- {INES, dialogues/holeegram.moon}
t[296] = "Glem det."  -- {ECHO, dialogues/holeegram.moon}
t[579] = "Trenger bare et par sekunder."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[580] = "Det er en gammel modell."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[581] = "Resultatet er klart!"  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[582] = "Vi hadde flaks!"  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[583] = "Det er veldig enkelt."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[584] = "Vi trenger bare:"  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[585] = "En kraftig MAGNET..."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[586] = "...og den MYNTEN bakerst i museet."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[297] = "Hvor kan jeg finne en magnet?"  -- {ECHO, dialogues/holeegram.moon}
t[298] = "Jeg tipper det er mer enn nok av dem her i framtiden."  -- {INES, dialogues/holeegram.moon}
t[587] = "Øh, ikke nå lenger."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[588] = "Ikke siden ulykken."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[299] = "...Ok."  -- {INES, dialogues/holeegram.moon}
t[300] = "Andre tidslinjer, blir det."  -- {INES, dialogues/holeegram.moon}
t[301] = "At det må være nøyaktig den mynten virker litt underlig."  -- {ECHO, dialogues/holeegram.moon}
t[589] = "Vel, teknisk sett trenger jeg bare gull."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[590] = "Jeg ville bare gjøre det lett for deg."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[302] = "Men jeg kan jo ikke nå den!"  -- {INES, dialogues/holeegram.moon}
t[303] = "Kan jeg ikke bare lete etter noe annet i gull?"  -- {INES, dialogues/holeegram.moon}
t[591] = "Nei, det finnes ingen annen gull i dette spillet."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[592] = "Beklager."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[304] = "Søren."  -- {INES, dialogues/holeegram.moon}
t[305] = "Jeg skjønner, takk."  -- {ECHO, dialogues/holeegram.moon}
t[306] = "Sekstitallet."  -- {NOECHO, dialogues/navigator.moon}
t[307] = "Nittitallet."  -- {NOECHO, dialogues/navigator.moon}
t[308] = "Nåtid."  -- {NOECHO, dialogues/navigator.moon}
t[309] = "FRAMTIDEN."  -- {NOECHO, dialogues/navigator.moon}
t[310] = "Bli her."  -- {NOECHO, dialogues/navigator.moon}
t[316] = "Er det over?"  -- {INES, dialogues/ending.moon}
t[317] = "Er dette den riktige tidsperioden?"  -- {INES, dialogues/ending.moon}
t[593] = "Ines, jenta mi!"  -- {LEE, dialogues/ending.moon}
t[594] = "Du klarte det!"  -- {LEE, dialogues/ending.moon}
t[595] = "Hva var det som tok så lang tid?"  -- {LEE, dialogues/ending.moon}
t[318] = "HVA MENER DU MED \"HVA VAR DET SOM TOK SÅ LANG TID\"?!"  -- {INES, dialogues/ending.moon}
t[319] = "DU FORLOT MEG SITTENDE FAST I EN TIDSTUNELL!"  -- {INES, dialogues/ending.moon}
t[596] = "Gjorde jeg det?"  -- {LEE, dialogues/ending.moon}
t[320] = "Den dumme knappen din fungerte bare på deg!"  -- {INES, dialogues/ending.moon}
t[597] = "Åjo, det hadde jeg glemt."  -- {LEE, dialogues/ending.moon}
t[598] = "Men du ser jo ut til å ha klart deg ganske bra."  -- {LEE, dialogues/ending.moon}
t[599] = "Du har alltid vært ressursterk."  -- {LEE, dialogues/ending.moon}
t[321] = "*Surmuler*"  -- {INES, dialogues/ending.moon}
t[600] = "Du endret ingenting i fortiden, ikke sant?"  -- {LEE, dialogues/ending.moon}
t[322] = "Øhm..."  -- {INES, dialogues/ending.moon}
t[323] = "Definér \"endring\"."  -- {INES, dialogues/ending.moon}
t[601] = "Oisann."  -- {LEE, dialogues/ending.moon}
t[602] = "Kanskje du vil ta et par skritt framover."  -- {LEE, dialogues/ending.moon}
t[603] = "Hva er det som skjer her?"  -- {COLLECTOR, dialogues/ending.moon}
t[324] = "Å nei."  -- {INES, dialogues/ending.moon}
t[604] = "Hvor er min samling?!"  -- {COLLECTOR, dialogues/ending.moon}
t[605] = "Oj!"  -- {PAOLO, dialogues/ending.moon}
t[606] = "Å..."  -- {COLLECTOR, dialogues/ending.moon}
t[607] = "...Herre..."  -- {COLLECTOR, dialogues/ending.moon}
t[608] = "...Gud."  -- {COLLECTOR, dialogues/ending.moon}
t[609] = "Er dere..."  -- {COLLECTOR, dialogues/ending.moon}
t[610] = "Gutta, sjekk det blikket!"  -- {ANDREA, dialogues/ending.moon}
t[611] = "Jeg tror hun er..."  -- {PAOLO, dialogues/ending.moon}
t[612] = "...EN FAN!"  -- {PAOLO, dialogues/ending.moon}
t[613] = "Har dere lagt merke til at alle fansene våre ser litt vel strenge ut?"  -- {PEPPE, dialogues/ending.moon}
t[325] = "Jeg er ikke fan av dere!"  -- {INES, dialogues/ending.moon}
t[614] = "Jeg ser vel ikke streng ut!"  -- {LEE, dialogues/ending.moon}
t[615] = "DET ER BANDET!"  -- {COLLECTOR, dialogues/ending.moon}
t[326] = "Hva har jeg gjort."  -- {INES, dialogues/ending.moon}
t[616] = "HVEM VIL VÆRE MED PÅ TUR TIL FENFEFVANNET?"  -- {LEE, dialogues/ending.moon}
t[617] = "Jeg! Jeg vil!"  -- {PEPPE, dialogues/ending.moon}
t[618] = "Hvada?-vannet"  -- {ANDREA, dialogues/ending.moon}
t[619] = "Vi er på turné! Fett!"  -- {PAOLO, dialogues/ending.moon}
t[620] = "Jeg drar hvor de enn skal."  -- {COLLECTOR, dialogues/ending.moon}
t[327] = "Burde vi ikke prøve å sende dem tilbake til tidslinjene sine?"  -- {INES, dialogues/ending.moon}
t[621] = "Næ, vi ordner det senere."  -- {LEE, dialogues/ending.moon}
t[622] = "Vi har nok tid."  -- {LEE, dialogues/ending.moon}
t[623] = "Så: har du lært noe nyttig av denne opplevesen?"  -- {LEE, dialogues/ending.moon}
t[328] = "Å aldri stole på dingsene dine."  -- {ECHO, dialogues/ending.moon}
t[624] = "Det sier du alltid."  -- {LEE, dialogues/ending.moon}
t[329] = "Du er enda rarere i framtiden."  -- {ECHO, dialogues/ending.moon}
t[625] = "Det håper jeg virkelig, jeg øver på det hver dag."  -- {LEE, dialogues/ending.moon}
t[330] = "Jeg burde stille som presidentkandidat."  -- {ECHO, dialogues/ending.moon}
t[626] = "\"President Ines\""  -- {LEE, dialogues/ending.moon}
t[627] = "Det låter fint."  -- {LEE, dialogues/ending.moon}
t[331] = "Aldri betal 0 kr for et pay-what-you-want point & click eventyrspill."  -- {ECHO, dialogues/ending.moon}
t[628] = "Kloke ord."  -- {LEE, dialogues/ending.moon}
t[629] = "OK FOLKENS!"  -- {LEE, dialogues/ending.moon}
t[630] = "LA OSS SYNGE NOEN TURSANGER!"  -- {LEE, dialogues/ending.moon}
t[631] = "Vi kan spille til!"  -- {PAOLO, dialogues/ending.moon}
t[632] = "JAA!!!"  -- {COLLECTOR, dialogues/ending.moon}
t[332] = "...dette blir en lang tur."  -- {INES, dialogues/ending.moon}
t[333] = "Tilbake til spillet"  -- {TEXT, gui/options.moon}
t[335] = "Musikkvolum"  -- {TEXT, gui/options.moon}
t[649] = "Fullskjerm"  -- {TEXT, gui/options.moon}
t[650] = "Hopp over samtaler med venstre museknapp"  -- {TEXT, gui/options.moon}
t[651] = "Hopp over samtaler med høyre museknapp"  -- {TEXT, gui/options.moon}
t[344] = "Start spill"  -- {TEXT, gui/start.moon}
t[345] = "Valg"  -- {TEXT, gui/start.moon}
t[652] = "Norsk"  -- {TEXT, gui/start.moon}
t[346] = "Skapt, skrevet og designet av"  -- {TEXT, credits.moon}
t[347] = "Programmering"  -- {TEXT, credits.moon}
t[348] = "Illustrasjoner og animasjon"  -- {TEXT, credits.moon}
t[349] = "Musikk"  -- {TEXT, credits.moon}
t[350] = "Ekstra illustrasjoner og animasjon"  -- {TEXT, credits.moon}
t[351] = "Lyddesign"  -- {TEXT, credits.moon}
t[653] = "LanaPixel Font"  -- {TEXT, credits.moon}
t[352] = "Skapt med"  -- {TEXT, credits.moon}
t[353] = "Lydmotor"  -- {TEXT, credits.moon}
t[354] = "GUI Rammeverk"  -- {TEXT, credits.moon}
t[356] = "Takk for at du spilte!"  -- {TEXT, credits.moon}

return t
